---
# vars file for mac
homebrew_packages:
  - name: tree
    state: latest
  - name: git-lfs
    state: latest
  - name: python3
    state: latest
  - name: wget
    state: latest
  - name: node
    state: latest
  - name: tig
    state: latest
  - name: hugo
    state: latest
  - name: terraform
    state: latest
  - name: bat
    state: latest
  - name: colordiff
    state: latest
  - name: nkf
    state: latest
  - name: pipenv
    state: absent
  - name: peco
    state: latest
  - name: fish
    state: latest
  - name: awscli
    state: latest
  - name: iperf
    state: latest
  - name: git
    state: latest
  - name: macvim
    state: latest
  - name: git-secrets
    state: latest
  - name: jump
    state: latest
  - name: jq
    state: latest
  - name: fzf
    state: latest
  - name: gh
    state: latest
  - name: starship
    state: latest

homebrew_cask_packages:
  - name: 1password-cli
    state: latest
  - name: session-manager-plugin
    state: latest

homebrew_tap_packages:
  - name: aws/tap
    state: present

git_configurations: "{{ git_configurations_base + git_configurations_macos }}"

git_configurations_macos:
  - name: credential.helper
    value: osxkeychain
    scope: global

osx_defaults_configurations:
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: boolean
    value: true
    state: present

nodejs_npm:
  - name: prh
    global: yes
    state: present

oh_my_zsh:
  dest: ~/.oh-my-zsh

zsh_peco_history:
  repo: git@github.com:jimeh/zsh-peco-history.git
  dest: ~/.zsh/zsh-peco-history