---
# defaults file for common
dev_directories:
  - name: Create read only git repo directory
    path: ~/dev/readonly
    state: directory
  - name: Create workspace directory
    path: ~/dev/workspace
    state: directory

dotfile_repo:
  repo: git@github.com:nikuyoshi/dotfiles.git
  dest: ~/dev/workspace/dotfiles
