---
# tasks file for cloudshell
- name: Check the git directory status
  stat:
    path: "{{ dotfile_repo.dest }}"
  register: dotfile_repo_directory

- name: Update yum and install softwares
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items: "{{ yum_packages }}"
  become: true

- name: Get latest peco version
  shell: >
    curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^location:/{print $NF}'
  register: peco_latest_version

- name: Download latest peco
  get_url: url=https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz dest=/tmp/peco_linux_amd64.tar.gz

- name: Extract peco
  unarchive: src=/tmp/peco_linux_amd64.tar.gz dest=/tmp/

- name: Copy to /usr/bin/
  copy: src=/tmp/peco_linux_amd64/peco dest=/usr/bin/ mode=0755
  become: true

- name: Configure git_config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: "{{ item.scope }}"
  with_items: "{{ git_configurations }}"

- name: Create directory for local development
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items: "{{ dev_directories }}"

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfile_repo.repo }}"
    dest: "{{ dotfile_repo.dest }}"
    clone: yes
  when:
    - not dotfile_repo_directory.stat.exists

- name: Update dotfiles repository
  git:
    repo: "{{ dotfile_repo.repo }}"
    dest: "{{ dotfile_repo.dest }}"
    clone: no
    track_submodules: yes
    update: yes
  when:
    - dotfile_repo_directory.stat.exists

- name: Setup dotfile settings
  shell:
    cmd: bash ~/dev/workspace/dotfiles/setup.sh

- name: Download oh-my-fish
  get_url:
    url: https://get.oh-my.fish
    dest: ~/oh-my-fish-installer.sh
    mode: 0755

- name: Install oh-my-fish      
  shell: 
    cmd: ~/oh-my-fish-installer.sh -y --noninteractive
  args:
    executable: /usr/bin/fish

- name: Install fish theme
  shell: 
    cmd: omf install robbyrussell
  args:
    executable: /usr/bin/fish

- name: Install peco plugin
  shell: 
    cmd: omf install peco
  args:
    executable: /usr/bin/fish

- name: Modify shell with script
  copy:
    dest={{ ansible_env.HOME }}/.bashrc
    content="/usr/bin/fish"