---
# tasks file for cloudshell
- name: Update yum and install softwares
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items: "{{ yum_packages }}"
  become: true

- name: Get latest peco version
  shell: >
    curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^location:/{print $NF}'
  register: peco_latest_version

- name: Download latest peco
  get_url: url=https://github.com/peco/peco/releases/download/{{ peco_latest_version.stdout }}/peco_linux_amd64.tar.gz dest=/tmp/peco_linux_amd64.tar.gz

- name: Extract peco
  unarchive: src=/tmp/peco_linux_amd64.tar.gz dest=/tmp/

- name: Copy to /usr/bin/
  copy: src=/tmp/peco_linux_amd64/peco dest=/usr/bin/ mode=0755
  become: true


- name: Download oh-my-fish
  get_url:
    url: https://get.oh-my.fish
    dest: ~/oh-my-fish-installer.sh
    mode: 0755

- name: Install oh-my-fish      
  shell: 
    cmd: ~/oh-my-fish-installer.sh -y --noninteractive
  args:
    executable: /usr/bin/fish

- name: Install fish theme
  shell: 
    cmd: omf install robbyrussell
  args:
    executable: /usr/bin/fish

- name: Install peco plugin
  shell: 
    cmd: omf install peco
  args:
    executable: /usr/bin/fish


- name: Add Fish shell to .bashrc
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      # Launch Fish shell if available
      if [ -x /usr/bin/fish ] && [ -z "$FISH_LAUNCHED" ]; then
        export FISH_LAUNCHED=1
        exec /usr/bin/fish
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Fish shell"
    insertafter: EOF