---
# vars file
apt_packages:
  - name: tree
    state: latest
  - name: git-lfs
    state: latest
  - name: python3
    state: latest
  - name: jq
    state: latest
  - name: wget
    state: latest
  - name: nodejs
    state: latest
  - name: tig
    state: latest
  - name: hugo
    state: latest
  - name: bat
    state: latest
  - name: colordiff
    state: latest
  - name: nkf
    state: latest
  - name: pipenv
    state: absent
  - name: peco
    state: latest
  - name: fish
    state: latest
  - name: 1password-cli
    state: latest
  - name: awscli
    state: latest
  - name: iperf
    state: latest
  - name: git
    state: latest
  - name: jupyter
    state: latest
  - name: git-secrets
    state: latest
  - name: keychain
    state: latest
  - name: gh
    state: latest
  - name: terraform
    state: latest

git_configurations: "{{ git_configurations_base }}"