---
# vars file for cloudshell
yum_packages:
  - name: https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_8/x86_64/fish-3.1.2-1.11.x86_64.rpm
    state: present
  - name: tig
    state: latest
  - name: hostname
    state: latest

git_configurations: "{{ git_configurations_base }}"

# Cloud Shell uses HTTPS URL instead of SSH
dotfile_repo:
  repo: "https://github.com/{{ github_username }}/dotfiles.git"
  dest: ~/dev/workspace/dotfiles
