---
# vars file for cloudshell
yum_packages:
  - name: https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_8/x86_64/fish-3.1.2-1.11.x86_64.rpm
    state: present
  - name: tig
    state: latest
  - name: hostname
    state: latest

git_configurations:
  - name: user.name
    value: Hiroki Uchida
    scope: global
  - name: user.email
    value: "{{ git_user_email }}"
    scope: global
  - name: merge.tool
    value: vimdiff
    scope: global
  - name: core.editor
    value: vim
    scope: global

# Cloud Shell uses HTTPS URL instead of SSH
dotfile_repo:
  repo: https://github.com/nikuyoshi/dotfiles.git
  dest: ~/dev/workspace/dotfiles
