---
# vars file for cloudshell
dotfile_repo:
  repo: git@github.com:nikuyoshi/dotfiles.git
  dest: ~/dev/workspace/dotfiles

yum_packages:
  - name: fish
    state: latest
  - name: tig
    state: latest
  - name: hostname
    state: latest

git_configurations:
  - name: user.name
    value: Hiroki Uchida
    scope: global
  - name: merge.tool
    value: vimdiff
    scope: global
  - name: core.editor
    value: vim
    scope: global

dev_directories:
  - name: Create read only git repo directory
    path: ~/dev/readonly
    state: directory
  - name: Create workspace directory
    path: ~/dev/workspace
    state: directory

dotfile_repo:
  repo: https://github.com/nikuyoshi/dotfiles.git
  dest: ~/dev/workspace/dotfiles
