---
# vars file for mac
homebrew_packages:
  - name: tree
    state: latest
  - name: git-lfs
    state: latest
  - name: gradle
    state: latest
  - name: python3
    state: latest
  - name: jq
    state: latest
  - name: wget
    state: latest
  - name: node
    state: latest
  - name: mercurial
    state: latest
  - name: postgresql
    state: latest
  - name: tig
    state: latest
  - name: yarn
    state: latest
  - name: hugo
    state: latest
  - name: terraform
    state: latest
  - name: bat
    state: latest
  - name: colordiff
    state: latest
  - name: maven
    state: latest
  - name: nkf
    state: latest
  - name: pipenv
    state: absent
  - name: aws-sam-cli
    state: latest
  - name: peco
    state: latest
  - name: go
    state: latest
  - name: fish
    state: latest
  - name: awscli
    state: latest
  - name: iperf
    state: latest

homebrew_cask_packages:
  - name: ngrok
    state: present

homebrew_tap_packages:
  - name: aws/tap
    state: present

git_configurations:
  - name: user.name
    value: Hiroki Uchida
    scope: global
  - name: credential.helper
    value: osxkeychain
    scope: global
  - name: merge.tool
    value: vimdiff
    scope: global

osx_defaults_configurations:
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: boolean
    value: true
    state: present

dev_directories:
  - name: Create read only git repo directory
    path: ~/dev/readonly
    state: directory
  - name: Create workspace directory
    path: ~/dev/workspace
    state: directory

nodejs_npm:
  - name: prh
    global: yes
    state: present