---
# tasks file for ubuntu
- name: Add 1Password GPG key
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present
  become: true

- name: Add 1Password repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present
  become: true

- name: Install Terraform from HashiCorp
  block:
    - name: Add HashiCorp GPG key
      ansible.builtin.apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        state: present
      become: true

    - name: Add HashiCorp repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: hashicorp
        state: present
      become: true

- name: Update apt and install softwares
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items: "{{ apt_packages }}"
  become: true

- name: Install Jump
  snap: 
    name: jump




- name: Change default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/fish